# This configuration is for ESPnet2 to train Tacotron 2. Compared to the
# original paper, this configuration additionally use the guided attention
# loss to accelerate the learning of the diagonal attention. It requires
# only a single GPU with 12 GB memory and it takes ~3 days to finish the
# training on Titan V.

##########################################################
#                  TTS MODEL SETTING                     #
##########################################################
tts: gradtts                     # model architecture
tts_conf:                        # keyword arguments for the selected model
    adim: 192 # == grad-tts n_enc_channels
    aheads: 2 # == grad-tts n_heads
    elayers: 6 # == grad-tts n_enc_layers
    eunits: 768 # == grad-tts filter_channels
    positionwise_conv_kernel_size: 3 # == grad-tts enc_kernel
    
##########################################################
#                  OPTIMIZER SETTING                     #
##########################################################
optim: adam           # optimizer type
optim_conf:           # keyword arguments for selected optimizer
    lr: 1.0e-03       # learning rate
    eps: 1.0e-06      # epsilon
    weight_decay: 0.0 # weight decay coefficient

##########################################################
#                OTHER TRAINING SETTING                  #
##########################################################
num_iters_per_epoch: 500    # number of iterations per epoch
max_epoch: 10000            # number of epochs
grad_clip: 1.0              # gradient clipping norm
grad_noise: false           # whether to use gradient noise injection
accum_grad: 1               # gradient accumulation
# batch_bins: 1600000       # batch bins (for feats_type=fbank)
batch_bins: 5120000         # batch bins (for feats_type=raw, *= n_shift / n_mels)
batch_type: numel           # how to make batch
sort_in_batch: descending   # how to sort data in making batch
sort_batch: descending      # how to sort created batches
num_workers: 1              # number of workers of data loader
train_dtype: float32        # dtype in training
log_interval: null          # log interval in iterations
keep_nbest_models: 5        # number of models to keep
num_att_plot: 3             # number of attention figures to be saved in every check
seed: 0                     # random seed number
best_model_criterion:
-   - valid
    - loss
    - min
-   - train
    - loss
    - min
